server:
  port: 8098

spring.datasource:
  url: jdbc:h2:mem:jpa-practice;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
  username: sa

spring.jpa:
  database: MYSQL
  showSql: true
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  properties.hibernate.hbm2ddl.auto: update

logging.level:
  jpa.springboot.dmp: DEBUG
  org.springframework: INFO